name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to deploy'
        required: true
        type: string
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
  repository_dispatch:
    types: [release]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false
          repository: 'foxxmd/multi-scrobbler'
          ref: "${{ github.event.client_payload.commit || inputs.commit }}"
          path: 'ms'
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f #6.3.0
        with:
          node-version: 24
          # cannot use cache: 'npm'
          # because working directory isn't default https://github.com/actions/setup-node/issues/706#issuecomment-1467218211

      - name: Install app dev dependencies
        run: npm ci
        working-directory: ms
      - name: Generate schema files
        run: npm run schema
        working-directory: ms
      - name: Install docusaurus dependencies
        run: npm ci
        working-directory: ms/docsite
      - name: Build website
        env:
          RY_ANALYTICS: ${{ vars.RY_ANALYTICS }}
          RY_ANALYTICS_SITEID: ${{ vars.RY_ANALYTICS_SITEID }}
          BASE_SITE: ${{ vars.BASE_SITE }}
          DOCS_BASE: '/'
        run: npm run build
        working-directory: ms/docsite
      - name: Copy CNAME
        run: cp CNAME ms/docsite/build/CNAME
      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e #4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ms/docsite/build